### ISSUE TITLE
Animating the tooltip

### ISSUE THREAD

**Issue by rrag** [WaiSiuKei/finscript#1]
I love the animation of the tooltip you have, where it comes from the last known position to the current mouse position. Could you share how you did that?

I implemented a similar tooltip for a chart I made which uses d3-force simulation to generate the animated tooltip moving from the last known position to the current mouse position

http://marketdepth.reactstockcharts.org.s3-website-us-east-1.amazonaws.com/index.html

but here, the tooltip moves like an elastic, where it moves beyond the mouse position and then dampens  back to the right position. Just curious to see what you have used.

**Comment by WaiSiuKei** [comment]
I am using the opensource [EChart](https://github.com/ecomfe/echarts) , you can find its repo for more detail. :)

**Comment by WaiSiuKei** [comment]
@rrag I have updated a minimal demo for it , [tooltip-demo](https://github.com/WaiSiuKei/tooltip-demo) repo.
