### ISSUE TITLE
Sample code for VWAP

### ISSUE THREAD

**Issue by GoChartingAdmin** [WaiSiuKei/finscript#5]
Please help me with a sample code to create a volume weighted moving average (VWAP).  I think we would need to use a for loop and an example would go a long way.  Appreciate this repo.

**Comment by WaiSiuKei** [comment]
3-Day VWMA, here ya go
```
v0 = V
v1 = REF(V, 1)
v2 = REF(V, 2)
c0 = C
c1 = REF(C, 1)
c2 = REF(C, 2)
vwma = (c0*v0 + c1*v1 + c2*v2) / (v0+ v1+ v2)
return vwma
```
